version: '3.7'

services:
  p1exporter:
    image: revenberg/p1exporter
    container_name: p1exporter
    environment:
      - PROMETHEUS_PORT=9005
      - LOG_LEVEL=DEBUG
      - P1_DEVICE=/dev/ttyUSB0
      - P1_BAUDRATE=115200
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always   
    ports:
      - 9005:9005
    expose:
      - 9005